package PageUIs;

public class CustomerInfoPageUI {
	public static final String ADDRESS_LINK = "//div[@class ='master-wrapper-content']//a[text()='Addresses']";
	public static final String GENDER_RADIO = "//input[@id='gender-female']";
	public static final String FIRST_NAME_TEXTBOX = "//input[@id='FirstName']";
	public static final String LAST_NAME_TEXTBOX = "//input[@id='LastName']";
	public static final String DATE_OF_BIRTH_DAY_DROPDOWN_LIST = "//select[@name ='DateOfBirthDay']";
	public static final String DATE_OF_BIRTH_MONTH_DROPDOWN_LIST = "//select[@name ='DateOfBirthMonth']";
	public static final String DATE_OF_BIRTH_YEAR_DROPDOWN_LIST = "//select[@name ='DateOfBirthYear']";
	public static final String EMAIL_TEXTBOX = "//input[@id='Email']";
	public static final String COMPANY_TEXTBOX = "//input[@id='Company']";
	public static final String SAVE_BUTTON = "//button[@id='save-info-button']";
	public static final String POPUP = "//span[@class ='close']";
	public static final String CUSTOMER_INFO_LINK = "//a[text()='Customer info']";
	public static final String ADD_NEW_BUTTON = "//button[contains(@class,'add-address-button')]";
	public static final String ADD_FIRST_NAME_TEXTBOX = "//input[@id='Address_FirstName']";
	public static final String ADD_LAST_NAME_TEXTBOX = "//input[@id='Address_LastName']";
	public static final String ADD_EMAIL_TEXTBOX = "//input[@id='Address_Email']";
	public static final String ADD_COUNTRY_DROPDOWN_LIST = "//select[@id ='Address_CountryId']";
	public static final String ADD_CITY_TEXTBOX = "//input[@id='Address_City']";
	public static final String ADD_PHONE_NUMBER_TEXTBOX = "//input[@id='Address_PhoneNumber']";
	public static final String ADD_ADDRESS_1_TEXTBOX = "//input[@id='Address_Address1']";
	public static final String ADD_ZIP_POSTAL_CODE_TEXTBOX = "//input[@id='Address_ZipPostalCode']";
	public static final String SAVE_ADDRESS_BUTTON = "//button[contains(@class,'save-address-button')]";
	public static final String TITLE_RESULT = "//div[@class='section address-item']//strong";
	public static final String ADD_NAME_UPDATED = "//li[@class = 'name']";
	public static final String ADD_EMAIL_UPDATED = "//li[@class = 'email']";
	public static final String ADD_PHONE_UPDATED = "//li[@class = 'phone']";
	public static final String ADD_ADDRESS1_UPDATED = "//li[@class = 'address1']";
	public static final String ADD_CITY_STATE_ZIP_UPDATED = "//li[@class = 'city-state-zip']";
	public static final String ADD_COUNTRY_UPDATED = "//li[@class = 'country']";
	public static final String ADD_SUCCESSFUL_NOTI_BAR = "//div[@class='bar-notification success']//p";
	public static final String ADD_SUCCESSFUL_NOTI_CLOSE_ICON = "//div[@class='bar-notification success']//span";
	public static final String CHANGE_PASSWORD_LINK = "//div[@class ='master-wrapper-content']//a[text()='Change password']";
	public static final String OLD_PASSWORD_TEXTBOX = "//input[@id='OldPassword']";
	public static final String NEW_PASSWORD_TEXTBOX = "//input[@id='NewPassword']";
	public static final String CONFIRM_NEW_PASSWORD_TEXTBOX = "//input[@id='ConfirmNewPassword']";
	public static final String CHANGE_PASSWORD_BUTTON = "//button[contains(@class,'change-password-button')]";
	public static final String SUCCESSFUL_NOTIFICATION_BAR = "//div[@class ='bar-notification success']//p";
	public static final String SUCCESSFUL_NOTIFICATION_CLOSE_ICON = "//div[@class ='bar-notification success']//span";
	public static final String LOGOUT_LINK = "//a[@class='ico-logout']";
	public static final String PRODUCT_LIST_COMPUTERS_LINK = "//ul[@class='top-menu notmobile']//a[text()='Computers ']";
	public static final String PRODUCT_DESKTOP_LINK = "//h2[@class='title']//a[text()=' Desktops ']";
	public static final String MY_PRODUCT_REVIEW_LINK = "//a[text()='My product reviews']";
	public static final String MY_PRODUCT_REVIEW_TITLE_TEXT = "//div[@class='review-title']//strong";
	public static final String MY_PRODUCT_REVIEW_BODY_TEXT = "//div[@class='review-text']";
}
